export const ERROR_CODES = {
    UNSUPPORTED_FILE: 'UNSUPPORTED_FILE',

    PROCESSING_FAILED: 'PROCESSING_FAILED',
    METADATA_FAILED: 'METADATA_FAILED',

    SAVE_FAILED: 'SAVE_FAILED',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
};